packages:
  - packages/*
catalog:
  typescript: ^5.6.3
  tslib: ^2.8.1
  "@emotion/react": ^11.14.0
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  framer-motion: ^11.11.17
  "@chakra-v2/react": 2.11.0-next.0
  chromatic: ^11.25.0
