packages:
  - packages/*
catalog:
  typescript: ^5.6.3
  tslib: ^2.8.1
  "@emotion/react": ^11.13.5
  "@emotion/styled": ^11.13.5
  react: ^18.3.1
  react-dom: ^18.3.1
  "@types/react": ^18.3.12
  "@types/react-dom": ^18.3.1
  framer-motion: ^11.11.17
  "@chakra-ui/react": ^2.8.2
  "@chakra-ui/system": ^2.6.2
  chromatic: ^11.25.0
