name: chromatic
on: push

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chakra-ui:
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm turbo run build-storybook
      - name: Chromatic - chakra-ui
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_CHAKRA_UI }}
          workingDir: ./packages/storybook-chakra-ui
          autoAcceptChanges: main
          storybookBuildDir: dist
