name: Chromatic
on: push

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chakra-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Rush (install)
        run: node ./common/scripts/install-run-rush.js install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/chakra-ui
      - name: Run tests
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/chakra-ui
          onlyChanged: true
          exitZeroOnChanges: false
      - name: Publish
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./packages/chakra-ui
          onlyChanged: true
          autoAcceptChanges: true
