name: CI
on: [push]

jobs:
  chakra-ui:
    name: chakra-ui - ${{ matrix.node }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.x", "14.x", "15.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: git fetch origin main:refs/remotes/origin/main -a

      - name: Rush (changes)
        run: node ./common/scripts/install-run-rush.js change -v

      - name: Install
        run: node ./common/scripts/install-run-rush.js install

      - name: Rebuild
        run: node ./common/scripts/install-run-rush.js rebuild --verbose

      - name: Lint
        run: node ./common/scripts/install-run-rush.js lint
