name: build_lint
on: [push]

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-lint:
    name: chakra-ui - ${{ matrix.node }} - ${{ matrix.os }}
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["22.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm turbo run build
      - run: pnpm turbo run lint
