name: size
on: [pull_request]
jobs:
  chakra-ui:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: node ./common/scripts/install-run-rush.js install
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: packages/chakra-ui/
          skip_step: install
